# -*- mode: ruby -*-
# vi: set ft=ruby :
# 현재의 파일이 ruby인것을 인식하도록 하는 호환코드
# ft는 file type의 약자

#================#
# Ansible Server #
#================#

# Vagrant.configure("2") : Vagrant version 2
# config.vm.define : vagrant 명령어를 사용할 때 이용될 tag
Vagrant.configure("2") do |config|
  config.vm.define "ansible-server" do |cfg|    
    cfg.vm.box = "centos/7"               # provisioning 할 운영체제를 선택
    cfg.vm.provider "virtualbox" do |vb|      
      vb.name = "Ansible-Server"          # 가상 머신 이름 지정
    end
    cfg.vm.host_name = "ansible-server"   # 가상 머신 Hostname 지정
    cfg.vm.network "private_network", ip: "192.168.56.10" # 네트워크 지정
    cfg.vm.network "forwarded_port", guest:22, host: 60010, auto_correct: true, id: "ssh"
    # host와 사용하게 될 공유폴더 지정
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y"
    cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end
